# Generated by Django 5.0.1 on 2024-11-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
